👋 **Привет, Родион!**

Меня зовут Арсен Абдулин, и я буду твоим ревьювером по проекту. Предлагаю общаться на «ты», если не против =) Моя цель — не поиск ошибок в твоей работе, а поделиться опытом и помочь успешно завершить проект, чтобы на шаг приблизиться к профессии специалиста по Data Science.

Видно, что ты очень старался, выполняя проект, у меня положительное впечатление о работе! Выполнены почти все ключевые этапы — нужно только поправить теоретическое доказательство. В остальном я отметил рекомендации.      

При проверке работ я делаю следующие комментарии:

<div class="alert alert-success">
<b>✔️ Зеленым цветом</b> отмечены удачные решения, на которые можно опираться в следующих проектах.</div>

<div class="alert alert-warning">
<b>⚠️ Желтым цветом</b> я отметил пункты, которые в следующий раз можно сделать по-другому. Одно-два таких замечания в проекте допускается, но если их много — проект следует доработать. </div>

<div class="alert alert-danger">
<b>🚫 Красным цветом</b> отмечены критические замечания, которые необходимо поправить, чтобы принять проект. </div>

Если какие-то моменты в задании для тебя были непонятны и у тебя есть ко мне вопросы — смело спрашивай 😊 Также ты можешь доработать места, где есть желтые комментарии в этом проекте (однако, это не обязательно).

Предлагаю работать над проектом в диалоге: если ты решишь что-то поменять по моим рекомендациям — пиши об этом (выбери для своих комментариев определенный цвет — так мне будет легче увидеть изменения). Пожалуйста не перемещай, не изменяй и не удаляй мои комментарии. Все это поможет сделать проверку твоего проекта оперативнее.

<div class="alert alert-info"> <b>ℹ️ Комментарий студента: </b> Пример комментария. </div>

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> На всякий случай, здесь я добавил дополнительные материалы по матрицам. Может пригодится =)
    
http://publish.sutd.ru/e_books/lin_alg_2013/html/matrix_33.html основные операции с матрицами    

https://python-scripts.com/numpy информация по numpy с примерами
    
https://ml-handbook.ru/chapters/linear_models/intro Можешь посмотреть вот здесь теорию по линейной регрессии и по матрицам в том числе.

Вот неплохая статья по основам матричных операций и линейным моделям, правда на английском языке:

https://jonathan-hui.medium.com/machine-learning-linear-algebra-a5b1658f0151

http://www.machinelearning.ru/wiki/images/b/bb/Sem08_factorizations.pdf по матричным разложениям
    
Как дополнение по матричным разложениями и теории машинного обучения можно посмотреть видеолекции К. Воронцова или Е. Соколова, они есть на Youtube.
    
</div>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> Хорошо, что добавил небольшое описание и содержание проекта — так постороннему человеку будет проще разобраться.
    
</div>

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np 

from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

RANDOM_STATE = np.random.RandomState(131296) 


<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> Необходимые библиотеки импортированы, все хорошо.
    
</div>

In [2]:
def first_analyze(data):
    rows, columns = data.shape
    print('='*50)
    print('Количество строк:', rows)
    print('Количество столбцов:', columns)
    display(data.head())
    display(data.describe())
    print(data.info())
    print('='*50)

In [3]:
data = pd.read_csv('/datasets/insurance.csv')
first_analyze(data)

Количество строк: 5000
Количество столбцов: 5


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
None


Данные предоставленны в подготовленном виде - пропуски отсутствуют, типы данных соответствуют содержанию, явных аномалий нет.

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> Данные загружены и изучены успешно! Здорово, что применил функцию для анализа датасета.
    
Как рекомендация, можно еще посмотреть матрицу корреляции числовых признаков.
    
</div>

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не изменится

**Обоснование:** 

Возьмём новую матрицу $Z$ как результат умножения исходной матрицы $X$ на произвольную обратимую матрицу $P$:

$$
Z = XP
$$

Запишем формулы предсказания и обучения с новой матрицей $Z$:

$$
a = Zw
$$

$$
w = (Z^T Z)^{-1} Z^T y
$$

Подставим формулу обучения в формулу предсказания:

$$
a = Z(Z^T Z)^{-1} Z^T y
$$

Заменим $Z$ на $XP$:

$$
a = XP((XP)^T XP)^{-1} (XP)^T y
$$

Используем свойство произведения транспонированных матриц:

$$
(AB)^T = B^T A^T 
$$

$$
a = XP (P^TX^T XP)^{-1} P^T X^T y
$$

Предположим, что в $(P^TX^T XP)^{-1}$ - $A = P^TX^T X$ и $B = P$, по свойству обратных матриц:

$$
(AB)^{-1} = B^{-1} A^{-1} 
$$

$$
a = XP P^{-1} (P^TX^T X)^{-1} P^T X^T y
$$

Предположим, что в $(P^TX^T X)^{-1}$ - $A = P^T$ и $B = X^T X$:

$$
a = X P P^{-1} (X^T X)^{-1} P^{T^{-1}} P^T X^T y
$$

Сократим $P$ и $P^{-1}$, $P^T$ и $P^{T^{-1}}$ - каждое из этих сокращений даст единичную матрицу $E$:

$$
a = X E (X^T X)^{-1} E X^T y
$$
$$
a = X (X^T X)^{-1} X^T y
$$

Таким образом мы вернулись к изначальной функции, то есть значение предсказаний $a$ не меняется из-за умножения на произвольную обратимую матрицу.

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера v3:</b> Отлично, теперь все правильно!
    
Работа принята, желаю успехов в дальнейшем обучении =)
   
</div>

<div class="alert alert-info"> <b>ℹ️ Комментарий студента: </b> Попытка номер три, немножко по другому пути пошёл, поподробнее с: </div>

<div class="alert alert-warning">
<b>⚠️ Комментарий ревьювера v2:</b> В доказательстве осталось поправить еще один момент: после раскрытия скобок матрица $P^T$ должна оказаться в правой части, а матрица $P$ — в левой.
    
В матричных выражениях, в отличие от алгебраических, мы не можем менять сомножители местами.
    
В данном случае пригодится сочетательное свойство:
    
$(ABC)^{-1} = (C)^{-1} (AB)^{-1}$
    
</div>

<div class="alert alert-danger">
<b>🚫 Комментарий ревьювера:</b> Ход доказательства правильный, то есть некоторые замечания.
    
В выражении $(X^T X)^{-1}$ нельзя раскрывать скобки, так как матрицы $X$ и $X^T$ прямоугольные и для них не существует обратных матриц, то есть нельзя записывать $(X^T)^{-1}$ и $X^{-1}$.
    
Удобно преобразовать выражение для $w_1$:
   
$w_1 = ((X_1)^T X_1)^{-1} (X_1)^T y$.

Сначала нужно раскрыть скобки в операции транспонирования $(XP)^T$, а затем извлечь из-за скобок матрицы $P$ и $P^T$, а выражение $(X^T X)^{-1}$ оставить без изменений.

</div>

## Алгоритм преобразования

**Алгоритм**

Для защиты данных клиентов будем применять следующий алгоритм:
1. Создадим производную квадратную матрицу, размер которой определяется количеством признаков;
2. Проверим обратимость созданной матрицы, и если она не обратима - создадим новую;
3. Проведём умножение матрицы признаков на нашу созданную матрицу.

**Обоснование**

На основании пункта 2 можно сделать вывод о том, что такое умножение не повлияет на качество модели линейной регрессии.

## Проверка алгоритма

Выделим признаки и целевой признак из исходных данных.

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> Хорошо, что разделил данные на обучающую и тестовую выборки.
    
</div>

In [4]:
features = data.drop(columns=['Страховые выплаты'])
target = data['Страховые выплаты']

Выделим тренировочную и тестовую выборки.

In [5]:
features_train, features_test, target_train, target_test = train_test_split(features,
                                                                            target,
                                                                            test_size=0.25,
                                                                            random_state=131296)

Создадим произвольную квадратную матрицу и проверим, обратима ли она.

In [6]:
def get_random_matrix(feature, random_state):
    return random_state.uniform(0, 1, size=(feature.shape[1], feature.shape[1]))

def is_matrix_invertible(matrix):
    return matrix.shape[0] == matrix.shape[1] and np.linalg.matrix_rank(matrix) == matrix.shape[0]

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> Здорово, что применяешь проверку через ранг матрицы!
    
</div>

In [7]:
random_matrix = get_random_matrix(features_train, RANDOM_STATE)

while not is_matrix_invertible(random_matrix):
    random_matrix = get_random_matrix(RANDOM_STATE)

print(random_matrix)

[[0.62063605 0.19425234 0.03265273 0.84807503]
 [0.57598613 0.6413164  0.26320144 0.75696421]
 [0.11985965 0.0692599  0.57589947 0.27058831]
 [0.59418245 0.41608542 0.93910849 0.97170892]]


Перемножим матрицу признаков на полученную случайную матрицу.

In [8]:
features_train_trans = features_train @ random_matrix
features_test_trans = features_test @ random_matrix

<div class="alert alert-warning">
<b>⚠️ Комментарий ревьювера:</b> Предпочтительнее использовать оператор @ при умножении матриц. Он строже, чем np.dot и допускает только матричное умножение.
    
Оператор @ вызывает метод np.matmul:
    
https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
    
</div>

<div class="alert alert-info"> <b>ℹ️ Комментарий студента: </b> Изначально использовал np.dot исходя из описания документации - при использовании с двумя двухметрыми матрицами np.dot работает как np.matmul, и конкретно в этом случае мы заранее знаем, что у нас действительно используется две двумерные матрицы.
    
Однако, там же указано, что в таком случае предпочтительнее использование @ (или np.matmul) - в дальнейшем так и буду делать с: </div>

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера v2:</b> Да, все верно — различия начинаются в случае трехмерных массивов =)
    
</div>

Сравним исходную матрицу features_train и features_train_trans.

In [9]:
display(features_train.head())
display(features_train_trans.head())

Пол  Возраст  Зарплата  Члены семьи
531     0     41.0   36000.0            1
4249    0     27.0   36100.0            3
783     0     40.0   39800.0            1
3923    1     41.0   48900.0            0
3414    1     29.0   57900.0            1

0            1             2             3
531   4339.157092  2520.066449  20744.111425   9773.186390
4249  4344.267617  2518.846180  20799.894769   9791.591140
783   4794.047785  2782.612752  22932.266224  10800.665003
3923  5885.373059  3413.297323  28172.308181  13263.651951
3414  6957.792278  4029.356709  33353.184137  15690.834877

Данные после преобразования не понятны и отличаются от исходных.

Обучим две модели линейной регрессии - model для исходных данных и model_trans для изменённых.

In [10]:
model = LinearRegression()
model.fit(features_train, target_train)
predictions = model.predict(features_test)
print(f'Метрика R2 для обычных данных: {r2_score(target_test, predictions)}')

model_trans = LinearRegression()
model_trans.fit(features_train_trans, target_train)
predictions = model_trans.predict(features_test_trans)
print(f'Метрика R2 для изменённых данных: {r2_score(target_test, predictions)}')

Метрика R2 для обычных данных: 0.4458031234426689
Метрика R2 для изменённых данных: 0.44580312344094886


Различия в метриках пренебрежимо малы и объясняются точностью хранения дробных данных.

<div class="alert alert-success">
<b>✔️ Комментарий ревьювера:</b> Качество предсказания действительно не изменяется, результат достигнут!
    
Еще могу порекомендовать вот такой материал:
    
https://habr.com/ru/post/479398/

https://habr.com/ru/company/vk/blog/478514/ Применение зашифрованных данных для машинного обучения

https://www.amazon.science/blog/machine-learning-models-that-act-on-encrypted-data#:~:text=Privacy%2Dpreserving%20machine%20learning%20 Privacy-preserving machine learning (PPML)
 
</div>

**Вывод**

Теоретическое предположение о том, что умножение матрицы признаков не будет влиять на точность метрики нашло практическое докозательство. Соответственно, такой метод защиты данных допустим к применению.

<font color=blue>
<b> ✔️ 👍Заключение ревьювера:</b> Родион, у тебя хорошая работа, получен положительный результат! 
   
Могу отметить грамотно составленный код, хорошую практическую часть =) 
    
Есть некоторые замечания — нужно поправить теоретическое доказательство. В остальном я отметил рекомендации!
    
Отправляю работу для ознакомления с ходом проверки, а также если есть вопросы — смело задавай их, я постараюсь тебе помочь 😊

Жду твоего ответа!
</font>

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования